services:

  eems_db:
    image: postgres:14.15-alpine3.21
    container_name: eems_db
    hostname: eems_db
    restart: unless-stopped
    ports:
      - 127.0.0.1:5432:5432
    env_file:
      - .env
    volumes:
      - C:/Users/john.ansa/Downloads/db_data:/var/lib/postgresql/data
    

  eems_db_admin:
    image: dpage/pgadmin4:latest
    container_name: eems_db_admin
    hostname: eems_db_admin
    restart: unless-stopped
    ports:
      - 5050:80
    env_file:
      - .env
